// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABnLt34_3Pv9dxzwHzsVGsRaX27qsk6fo',
    appId: '1:516741365479:android:0ef72d2ff224f11f726c42',
    messagingSenderId: '516741365479',
    projectId: 'fir-18e21',
    storageBucket: 'fir-18e21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw4qDTQg2hyj4lm9K-cB5ep0T5jnNrhw0',
    appId: '1:516741365479:ios:ee862ad1a228e276726c42',
    messagingSenderId: '516741365479',
    projectId: 'fir-18e21',
    storageBucket: 'fir-18e21.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw4qDTQg2hyj4lm9K-cB5ep0T5jnNrhw0',
    appId: '1:516741365479:ios:ee862ad1a228e276726c42',
    messagingSenderId: '516741365479',
    projectId: 'fir-18e21',
    storageBucket: 'fir-18e21.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

}